name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create PEM File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Copy Project to EC2
        run: |
          scp -o StrictHostKeyChecking=no \
          -i key.pem \
          -r . \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/app

      - name: Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i key.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd /home/ubuntu/app

          # install docker if missing
          if ! command -v docker >/dev/null 2>&1; then
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
          fi

          # stop old container
          sudo docker stop mynginx || true
          sudo docker rm mynginx || true

          # build image
          sudo docker build -t mynginx .

          # run container
          sudo docker run -d \
            --name mynginx \
            -p 80:80 \
            mynginx

          EOF
